### ISSUE TITLE
mod_agency

### ISSUE THREAD

**Issue by Merou63** [cavo789/mod_agency#1]
Bonjour,
Je viens d'installer mod_agency sur un Joomla 3.6 avec le template Hathor.
Le module est bien là et activé mais d'une part il n'apparait pas et, d'autre part, je ne vois pas ou mettre les infos comme vous l'indiquez, je rate probablement qqc mais quoi ?
Merci d'avance pour votre aide et conseils,
Marc.

**Comment by cavo789** [comment]
Bonjour Marc

Tu as raison.  J'étais convaincu d'avoir écrit cette partie-là et non, ce n'était pas fait.
Je viens d'écrire les lignes de code requises et j'ai donc publié une version 1.0.1 du module.  J'ai aussi modifié le fichier readme qui reprend maintenant une section "How to install" pour expliquer comment faire l'installation du module et comment le paramétrer.  Cela devrait répondre à ta question ci-dessus.

Bonne journée.
